serverUrl: https://intellifactory.com
shortTitle: IntelliFactory
title: IntelliFactory Blog
description: Building F# applications since 2004
masterUserDisplayName: IntelliFactory
masterLanguage: en
languages: "en->English,es->Spanish,hu->Hungarian"
users: "anton.tayanovskyy->Anton Tayanovskyy,btamas->Tamas Banka,denuziere->Loic Denuziere,diego.echeverri->Diego Echeverri,gansperger->Istvan Gansperger,granicz->Adam Granicz,jankoa->Andras Janko,joel.bjornson->Joel Bjornson,maciej.lopatka->Maciej Lopatka,ramon.snir->Ramon Snir,sfowler->Simon Fowler,vladimir.matveev->Vladimir Matveev"
pageSize: 24
categoriesCountIfNotAll: 30
githubRepo: https://github.com/IntelliFactory/blogs
